export const ariaLabel = {
  editFaq: 'Edit FAQ',
  deleteFaq: 'Delete FAQ',
  superchargeFaq: 'Supercharge FAQ',
  selectAllFaqs: 'Select all FAQs',
  saveFaqEdit: 'Save FAQ edit',
  cancelEdit: 'Cancel edit',
  superchargeSelected: 'Supercharge selected FAQs',
  deleteSelected: 'Delete selected FAQs',
  chatbotOptions: 'Chatbot options',
  confirmUserEmail: 'Confirm user email',
  copyWidgetUrl: 'Copy widget URL',
  copyEmbedCode: 'Copy embed code',
  toggleFollowUp: 'Toggle follow-up email',
  deleteFollowUpRule: 'Delete follow-up rule',
  moveRuleUp: 'Move rule up',
  moveRuleDown: 'Move rule down',
  toggleRule: 'Toggle rule',
  deleteRule: 'Delete rule',
  toggleChatbotActive: 'Toggle chatbot active status',
  deleteChatbot: 'Delete chatbot',
  selectAllUsers: 'Select all users',
  selectUser: 'Select user',
  resetMessageCount: 'Reset message count',
  deleteUser: 'Delete user',
  previousStep: 'Previous step',
  nextStep: 'Next step',
} as const;
