project_id = "rtnhlmmgvvfupbibyrhu"

[functions.chat]
verify_jwt = false

[functions.supercharge]
verify_jwt = false

[functions.generate-faqs]
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[functions.autopilot]
verify_jwt = false

[functions.rollback-faq]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false


